### ISSUE TITLE
Input Data

### ISSUE THREAD

**Issue by dorsa2** [fmikulasch/text-cnn#1]
Hey, looking at ur CNN source file I was wondering about the "anzart_gesuch_janein_mit_header.csv" input file, would you please explain about this file? I didnt find it in repository

**Comment by fmikulasch** [comment]
Hey, the file is a table containing data from property displays gathered from various sites. It has several columns with text of the author about what he's selling. "soll" is a boolean if he is selling or searching for the property (the variable i try to predict). I can't put it online as it is sensitive data, but if you have questions, please ask.

**Comment by dorsa2** [comment]
Thank you for description, Im looking to simulate your CNN, I want a preview of your data to simulate it, if its possible, sth like a screenshot or sth

**Comment by fmikulasch** [comment]
Sorry, but i can't. In any case the easiest would be to search for sample datasets. Just search for `sample text classification dataset`, you'll find something like [this](https://archive.ics.uci.edu/ml/datasets.html?format=&task=cla&att=&area=&numAtt=&numIns=&type=text&sort=nameUp&view=table). It's pretty much the same and the data is not as messy as the one I use. Good luck.
